# explororation 13 : 아이유팬이 좋아할 만한 다른 아티스트 찾기

**루브릭 1. CSR matrix가 정상적으로 만들어졌다.**  
사용자와 아이템 개수를 바탕으로 정확한 사이즈로 만들었다.

-> 진행될 예정입니다.

**루브릭 2. MF 모델이 정상적으로 훈련되어 그럴듯한 추천이 이루어졌다.**  
사용자와 아이템 벡터 내적수치가 의미있게 형성되었다.

-> 진행될 예정입니다.

**루브릭 3. 비슷한 영화 찾기와 유저에게 추천하기의 과정이 정상적으로 진행되었다.**  
MF모델이 예측한 유저 선호도 및 아이템간 유사도, 기여도를 측정하고 의미를 분석해보았다.

-> 진행될 예정입니다.

***

## 목차

### 1. 사전작업

#### 1.1. 모듈 불러오기

#### 1.2. 데이터 불러오기

#### 1.3. 중복치 제거, 결측치 제거, 정규화, 불용어 제거

#### 1.4. 이상치 제거

#### 1.5. 데이터셋 구성

#### 1.6. 데이터 토큰화

##### 1.6.1. train set 토큰화

##### 1.6.2. test set 토큰화

##### 1.6.3. zero padding

### 2. 모델 구성 및 학습

#### 2.1. 기존의 seq2seq 모델

#### 2.2. attention이 추가된 seq2seq 모델

#### 2.3. 모델 학습

#### 2.4. 추론 모델 구성

### 3. 결과

### 4. 회고

***

In [37]:
import numpy as np
import scipy
import implicit

print(np.__version__)
print(scipy.__version__)
print(implicit.__version__)

1.21.4
1.7.1
0.4.8

In [38]:
import os
rating_file_path=os.getenv('HOME') + '/aiffel/recommendata_iu/data/ml-1m/ratings.dat'
ratings_cols = ['user_id', 'movie_id', 'ratings', 'timestamp']
ratings = pd.read_csv(rating_file_path, sep='::', names=ratings_cols, engine='python', encoding = "ISO-8859-1")
orginal_data_size = len(ratings)
ratings.head()

   user_id  movie_id  ratings  timestamp
0        1      1193        5  978300760
1        1       661        3  978302109
2        1       914        3  978301968
3        1      3408        4  978300275
4        1      2355        5  978824291

In [39]:
# 3점 이상만 남깁니다.
ratings = ratings[ratings['ratings']>=3]
filtered_data_size = len(ratings)

print(f'orginal_data_size: {orginal_data_size}, filtered_data_size: {filtered_data_size}')
print(f'Ratio of Remaining Data is {filtered_data_size / orginal_data_size:.2%}')

orginal_data_size: 1000209, filtered_data_size: 836478
Ratio of Remaining Data is 83.63%

In [40]:
# ratings 컬럼의 이름을 counts로 바꿉니다.
ratings.rename(columns={'ratings':'counts'}, inplace=True)

In [41]:
ratings['counts']

0          5
1          3
2          3
3          4
4          5
          ..
1000203    3
1000205    5
1000206    5
1000207    4
1000208    4
Name: counts, Length: 836478, dtype: int64

In [42]:
# 영화 제목을 보기 위해 메타 데이터를 읽어옵니다.
movie_file_path=os.getenv('HOME') + '/aiffel/recommendata_iu/data/ml-1m/movies.dat'
cols = ['movie_id', 'title', 'genre'] 
movies = pd.read_csv(movie_file_path, sep='::', names=cols, engine='python', encoding='ISO-8859-1')
movies.head()

   movie_id                               title                         genre
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

## 13-2 데이터 탐색하기와 전처리

In [1]:
import pandas as pd
import os

fname = os.getenv('HOME') + '/aiffel/recommendata_iu/data/lastfm-dataset-360K/usersha1-artmbid-artname-plays.tsv'
col_names = ['user_id', 'artist_MBID', 'artist', 'play']   # 임의로 지정한 컬럼명
data = pd.read_csv(fname, sep='\t', names= col_names)      # sep='\t'로 주어야 tsv를 열 수 있습니다.  
data.head(10)

,user_id,artist_MBID,artist,play
0,00000c289a1829a808ac09c00daf10bc3c4e223b,3bd73256-3905-4f3a-97e2-8b341527f805,betty blowtorch,2137
1,00000c289a1829a808ac09c00daf10bc3c4e223b,f2fb0ff0-5679-42ec-a55c-15109ce6e320,die Ärzte,1099
2,00000c289a1829a808ac09c00daf10bc3c4e223b,b3ae82c2-e60b-4551-a76d-6620f1b456aa,melissa etheridge,897
3,00000c289a1829a808ac09c00daf10bc3c4e223b,3d6bbeb7-f90e-4d10-b440-e153c0d10b53,elvenking,717
4,00000c289a1829a808ac09c00daf10bc3c4e223b,bbd2ffd7-17f4-4506-8572-c1ea58c3f9a8,juliette & the licks,706
5,00000c289a1829a808ac09c00daf10bc3c4e223b,8bfac288-ccc5-448d-9573-c33ea2aa5c30,red hot chili peppers,691
6,00000c289a1829a808ac09c00daf10bc3c4e223b,6531c8b1-76ea-4141-b270-eb1ac5b41375,magica,545
7,00000c289a1829a808ac09c00daf10bc3c4e223b,21f3573f-10cf-44b3-aeaa-26cccd8448b5,the black dahlia murder,507
8,00000c289a1829a808ac09c00daf10bc3c4e223b,c5db90c4-580d-4f33-b364-fbaa5a3a58b5,the murmurs,424
9,00000c289a1829a808ac09c00daf10bc3c4e223b,0639533a-0402-40ba-b6e0-18b067198b73,lunachicks,403

In [2]:
len(data)

17535655

In [3]:
# 사용하는 컬럼만 남겨줍니다.
using_cols = ['user_id', 'artist', 'play']
data = data[using_cols]
data.head(10)

                                    user_id                   artist  play
0  00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b                die Ärzte  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5  00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6  00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7  00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8  00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9  00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403

In [4]:
data['artist'] = data['artist'].str.lower() # 검색을 쉽게 하기 위해 아티스트 문자열을 소문자로 바꿔줍시다.
data.head(10)

                                    user_id                   artist  play
0  00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b                die ärzte  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5  00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6  00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7  00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8  00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9  00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403

In [5]:
data[45:55]

                                     user_id                    artist   play
45  00000c289a1829a808ac09c00daf10bc3c4e223b                        l7    135
46  00000c289a1829a808ac09c00daf10bc3c4e223b                 bif naked    134
47  00000c289a1829a808ac09c00daf10bc3c4e223b                girlschool    134
48  00000c289a1829a808ac09c00daf10bc3c4e223b           the wallflowers    131
49  00001411dc427966b17297bf4d69e7e193135d89  the most serene republic  12763
50  00001411dc427966b17297bf4d69e7e193135d89                     stars   8192
51  00001411dc427966b17297bf4d69e7e193135d89       broken social scene   6413
52  00001411dc427966b17297bf4d69e7e193135d89                have heart   5361
53  00001411dc427966b17297bf4d69e7e193135d89           luminous orange   5120
54  00001411dc427966b17297bf4d69e7e193135d89                     boris   5110

In [6]:
data.loc[data['user_id']== data.loc[0, 'user_id']][:10]

                                    user_id                   artist  play
0  00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b                die ärzte  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5  00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6  00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7  00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8  00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9  00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403

In [7]:
len(data.loc[data['user_id']== data.loc[0, 'user_id']])

49

In [8]:
data['play'].is_monotonic_decreasing

False

In [9]:
# 유저 수
data['user_id'].nunique()

358868

In [10]:
# 아티스트 수
data['artist'].nunique()

291346

In [11]:
# 인기 많은 아티스트
artist_count = data.groupby('artist')['user_id'].count()
artist_count.sort_values(ascending=False).head(10)
# data.groupby('artist')['user_id'].count()[100:200]

artist
radiohead                77254
the beatles              76245
coldplay                 66658
red hot chili peppers    48924
muse                     46954
metallica                45233
pink floyd               44443
the killers              41229
linkin park              39773
nirvana                  39479
Name: user_id, dtype: int64

In [12]:
# 유저별 몇 명의 아티스트를 듣고 있는지에 대한 통계
# 각각의 유저들이 몇명의 아티스트들의 노래를 듣고 있는지
user_count = data.groupby('user_id')['artist'].count()
user_count.describe()

count    358868.000000
mean         48.863234
std           8.524272
min           1.000000
25%          46.000000
50%          49.000000
75%          51.000000
max         166.000000
Name: artist, dtype: float64

In [13]:
# 유저별 play횟수 중앙값에 대한 통계
# 각각의 유저들의 플레이 횟수의 중앙값
user_median = data.groupby('user_id')['play'].median()
user_median.describe()

count    358868.000000
mean        142.187676
std         213.089902
min           1.000000
25%          32.000000
50%          83.000000
75%         180.000000
max       50142.000000
Name: play, dtype: float64

In [14]:
# 본인이 좋아하시는 아티스트 데이터로 바꿔서 추가하셔도 됩니다! 단, 이름은 꼭 데이터셋에 있는 것과 동일하게 맞춰주세요. 
my_favorite = ['black eyed peas' , 'maroon5' ,'jason mraz' ,'coldplay' ,'beyoncé']

# 'zimin'이라는 user_id가 위 아티스트의 노래를 30회씩 들었다고 가정하겠습니다.
my_playlist = pd.DataFrame({'user_id': ['zimin']*5, 'artist': my_favorite, 'play':[30]*5})

if not data.isin({'user_id':['zimin']})['user_id'].any():  # user_id에 'zimin'이라는 데이터가 없다면
    data = data.append(my_playlist)                           # 위에 임의로 만든 my_favorite 데이터를 추가해 줍니다. 

data.tail(10)       # 잘 추가되었는지 확인해 봅시다.

               user_id           artist  play
17535650  sep 20, 2008       turbostaat    12
17535651  sep 20, 2008    cuba missouri    11
17535652  sep 20, 2008  little man tate    11
17535653  sep 20, 2008        sigur rós    10
17535654  sep 20, 2008       the smiths    10
0                zimin  black eyed peas    30
1                zimin          maroon5    30
2                zimin       jason mraz    30
3                zimin         coldplay    30
4                zimin          beyoncé    30

In [15]:
# 고유한 유저, 아티스트를 찾아내는 코드
user_unique = data['user_id'].unique()
artist_unique = data['artist'].unique()

# 유저, 아티스트 indexing 하는 코드 idx는 index의 약자입니다.
user_to_idx = {v:k for k,v in enumerate(user_unique)}
artist_to_idx = {v:k for k,v in enumerate(artist_unique)}

In [16]:
print(user_unique)
print(len(user_unique))
print(artist_unique)
print(len(artist_unique))

['00000c289a1829a808ac09c00daf10bc3c4e223b'
 '00001411dc427966b17297bf4d69e7e193135d89'
 '00004d2ac9316e22dc007ab2243d6fcb239e707d' ...
 'ffff9ef87a7d9494ada2f9ade4b9ff637c0759ac' 'sep 20, 2008' 'zimin']
358869
['betty blowtorch' 'die ärzte' 'melissa etheridge' ... 'sacred buddha'
 'cat lunette' 'suzanina']
291347

In [17]:
print(dict(list(user_to_idx.items())[:10]))
print(dict(list(artist_to_idx.items())[:10]))

{'00000c289a1829a808ac09c00daf10bc3c4e223b': 0, '00001411dc427966b17297bf4d69e7e193135d89': 1, '00004d2ac9316e22dc007ab2243d6fcb239e707d': 2, '000063d3fe1cf2ba248b9e3c3f0334845a27a6bf': 3, '00007a47085b9aab8af55f52ec8846ac479ac4fe': 4, '0000c176103e538d5c9828e695fed4f7ae42dd01': 5, '0000ee7dd906373efa37f4e1185bfe1e3f8695ae': 6, '0000ef373bbd0d89ce796abae961f2705e8c1faf': 7, '0000f687d4fe9c1ed49620fbc5ed5b0d7798ea20': 8, '0001399387da41d557219578fb08b12afa25ab67': 9}
{'betty blowtorch': 0, 'die ärzte': 1, 'melissa etheridge': 2, 'elvenking': 3, 'juliette & the licks': 4, 'red hot chili peppers': 5, 'magica': 6, 'the black dahlia murder': 7, 'the murmurs': 8, 'lunachicks': 9}

In [18]:
# 인덱싱이 잘 되었는지 확인해 봅니다. 
print(user_to_idx['zimin'])    # 358869명의 유저 중 마지막으로 추가된 유저이니 358868이 나와야 합니다. 
print(artist_to_idx['black eyed peas'])

358868
376

In [19]:
# indexing을 통해 데이터 컬럼 내 값을 바꾸는 코드
# dictionary 자료형의 get 함수는 https://wikidocs.net/16 을 참고하세요.

# user_to_idx.get을 통해 user_id 컬럼의 모든 값을 인덱싱한 Series를 구해 봅시다. 
# 혹시 정상적으로 인덱싱되지 않은 row가 있다면 인덱스가 NaN이 될 테니 dropna()로 제거합니다. 
temp_user_data = data['user_id'].map(user_to_idx.get).dropna()
if len(temp_user_data) == len(data):   # 모든 row가 정상적으로 인덱싱되었다면
    print('user_id column indexing OK!!')
    data['user_id'] = temp_user_data   # data['user_id']을 인덱싱된 Series로 교체해 줍니다. 
else:
    print('user_id column indexing Fail!!')

# artist_to_idx을 통해 artist 컬럼도 동일한 방식으로 인덱싱해 줍니다. 
temp_artist_data = data['artist'].map(artist_to_idx.get).dropna()
if len(temp_artist_data) == len(data):
    print('artist column indexing OK!!')
    data['artist'] = temp_artist_data
else:
    print('artist column indexing Fail!!')

data

user_id column indexing OK!!
artist column indexing OK!!

    user_id  artist  play
0         0       0  2137
1         0       1  1099
2         0       2   897
3         0       3   717
4         0       4   706
..      ...     ...   ...
0    358868     376    30
1    358868  270115    30
2    358868    3746    30
3    358868      62    30
4    358868     396    30

[17535660 rows x 3 columns]

## 13-4 사용자의 명시적/암묵적 평가

In [20]:
# 1회만 play한 데이터의 비율을 보는 코드
only_one = data[data['play']<2]
one, all_data = len(only_one), len(data)
print(f'{one},{all_data}')
print(f'Ratio of only_one over all data is {one/all_data:.2%}')  # f-format에 대한 설명은 https://bit.ly/2DTLqYU

147740,17535660
Ratio of only_one over all data is 0.84%

In [21]:
data[data['play']<2]

          user_id  artist  play
1854           38    1431     1
1855           38    1432     1
1856           38    1433     1
1857           38    1434     1
1858           38    1435     1
...           ...     ...   ...
17529425   358739   18774     1
17529426   358739   63246     1
17531174   358776   25658     1
17531175   358776   42866     1
17531176   358776    9899     1

[147740 rows x 3 columns]

한 번이라도 들었으면 선호한다고 판단한다.

많이 재생한 아티스트에 대해 가중치를 주어서 더 확실히 좋아한다고 판단한다.

## 13-5. Matrix Factorization(MF)

## 13-6. CSR(Compressed Sparse Row) Matrix

In [22]:
# 실습 위에 설명보고 이해해서 만들어보기
from scipy.sparse import csr_matrix

num_user = data['user_id'].nunique()
num_artist = data['artist'].nunique()

csr_data = csr_matrix((data.play, (data.user_id, data.artist)), shape= (num_user, num_artist))
csr_data

<358869x291347 sparse matrix of type '<class 'numpy.int64'>'
	with 17535578 stored elements in Compressed Sparse Row format>

In [23]:
csr_data.shape

(358869, 291347)

## 13-7. MF 모델 학습하기

In [26]:
from implicit.als import AlternatingLeastSquares
import os
import numpy as np

# implicit 라이브러리에서 권장하고 있는 부분입니다. 학습 내용과는 무관합니다.
os.environ['OPENBLAS_NUM_THREADS']='1'
os.environ['KMP_DUPLICATE_LIB_OK']='True'
os.environ['MKL_NUM_THREADS']='1'

In [27]:
# Implicit AlternatingLeastSquares 모델의 선언
als_model = AlternatingLeastSquares(factors=100, regularization=0.01, use_gpu=False, iterations=15, dtype=np.float32)

In [28]:
# als 모델은 input으로 (item X user 꼴의 matrix를 받기 때문에 Transpose해줍니다.)
csr_data_transpose = csr_data.T
csr_data_transpose

<291347x358869 sparse matrix of type '<class 'numpy.int64'>'
	with 17535578 stored elements in Compressed Sparse Column format>

In [29]:
# 모델 훈련
als_model.fit(csr_data_transpose)

  0%|          | 0/15 [00:00<?, ?it/s]

In [30]:
zimin, black_eyed_peas = user_to_idx['zimin'], artist_to_idx['black eyed peas']
zimin_vector, black_eyed_peas_vector = als_model.user_factors[zimin], als_model.item_factors[black_eyed_peas]

print('슝=3')

슝=3

In [35]:
print(zimin)
print(black_eyed_peas)

358868
376

In [36]:
als_model.user_factors[zimin]

array([ 0.22625405,  0.21813282,  0.8404122 , -0.3183336 ,  1.0544747 ,
        0.21347238,  0.22771811,  0.04060432, -0.28369406,  0.8945823 ,
        0.25868672, -0.39615703, -0.8301821 , -0.6991867 ,  0.7916298 ,
        0.07036909, -0.9373307 ,  0.5403258 ,  0.7623134 ,  0.3412103 ,
       -0.36074206,  0.77226496,  1.0462517 ,  0.04965759, -1.1075088 ,
        0.7444722 , -0.5161927 , -0.33093867,  1.2883573 , -0.02247125,
       -0.82692677,  0.49805698,  0.26982084,  0.32661816, -0.3518974 ,
        0.70347244, -0.47725108,  0.15936416, -0.6216651 , -1.0250742 ,
        0.2766337 ,  1.2641693 , -0.18440111,  0.26098958, -1.1516626 ,
       -0.03549235,  1.1825311 ,  0.0846125 ,  0.9751868 ,  0.7584146 ,
       -0.09698136,  1.1197466 ,  0.2899834 , -0.31268698, -0.36518243,
       -0.467355  , -0.01512995, -0.8612053 , -0.62506574, -1.1632082 ,
        0.71822053, -1.2466147 ,  0.83733535,  0.5483285 ,  0.50869864,
        0.09741828, -0.00170769, -0.69981027, -0.3991006 ,  0.47462893,
       -0.88861537, -0.42908737,  0.21305573, -0.07843318,  1.4916413 ,
        0.31504813,  0.2018416 , -0.0638586 ,  0.50778216, -1.5319299 ,
        0.3121036 , -0.65779686, -0.10395831, -0.5312231 , -0.05353422,
        0.41889334,  0.1582276 , -0.20009811, -0.3009032 ,  0.5364802 ,
        0.5203554 ,  0.06803278, -1.4897254 , -0.8812895 , -0.31822345,
        0.643884  ,  0.20621584, -0.5806608 , -0.16383174,  0.7058376 ],
      dtype=float32)